version: '3.8'

services:
  maildev:
    image: maildev/maildev
    environment:
      MAILDEV_INCOMING_USER: mailuser
      MAILDEV_INCOMING_PASS: mailpassword
    ports:
      - "1080:1080"
      - "1025:1025"
  db:
    image: postgres:12.14-alpine
    container_name: inclusion_numerique_pg
    environment:
      - POSTGRES_DB=${NEXT_PUBLIC_APP_SLUG}
      - POSTGRES_USER=${NEXT_PUBLIC_APP_SLUG}
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - inclusion_numerique-pgdata:/var/lib/postgresql/data
    networks:
      - inclusion_numerique-network

volumes:
  inclusion_numerique-pgdata:
    name: inclusion_numerique_pgdata

networks:
  inclusion_numerique-network:
    external: false
    name: inclusion_numerique-network

