version: '2'
services:
  web:
    container_name: inclusion_numerique
    image: ${DOCKER_COMPOSE_WEB_IMAGE}
    ports:
      - "3000:8080"
    environment:
      DATABASE_URL: ${DOCKER_COMPOSE_DATABASE_URL}
